### ISSUE TITLE
Disabling default features and specifying mysql feature fails to compile on 0.6.4

### ISSUE THREAD

**Issue by proudmuslim-dev** [Brendonovich/prisma-client-rust#246]
Toolchain: Stable (latest)

Dependencies:

```toml
[dependencies]
serde = "1"

[dependencies.prisma-client-rust]
git = "https://github.com/Brendonovich/prisma-client-rust"
tag = "0.6.4"
default-features = false
features = ["mysql"]

[dependencies.prisma-client-rust-cli]
git = "https://github.com/Brendonovich/prisma-client-rust"
tag = "0.6.4"
default-features = false
features = ["mysql"]
```

Error:
```rust
   Compiling sql-query-connector v0.1.0 (https://github.com/Brendonovich/prisma-engines?rev=43fcfd1b5c0be59e414fb03cf7b7712e1661b6d0#43fcfd1b)
error[E0599]: no method named `returning` found for struct `quaint::ast::Insert` in the current scope
  --> /home/user/.cargo/git/checkouts/prisma-engines-8e1416dd0e571d11/43fcfd1/query-engine/connectors/sql-query-connector/src/database/operations/upsert.rs:33:10
   |
33 |         .returning(selected_fields.as_columns())
   |          ^^^^^^^^^ private field, not a method
```

If I re-enable default features, it compiles without an issue

**Comment by Brendonovich** [comment]
Just pushed a quick update to 0.6.4 that fixes this, try `cargo update -p prisma-client-rust` to update

**Comment by proudmuslim-dev** [comment]
@Brendonovich It worked, thank you :)
